encoding: utf-8

# Site settings
title: Hush Owl | Silently observant
description: > # this means to ignore newlines until "baseurl:"
  Hush Owl is a documentary and story telling company.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hushowl.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Ignore files and folders
exclude: ['README.md','rental.md']
permalink: pretty

#social media links
facebook: "https://www.facebook.com/hushowl"
twitter: "http://twitter.com/hushowl"
instagram: "http://instagram.com/hushowl"
 